name: Build and Push image to docker hub
on:
  [workflow_dispatch]
  # push:
  #   branches:
  #     -main
  #   paths:
  #     - 'api/dockerfile'
  #     - 'front-end-nextjs'

jobs:
  publish_images:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Login to Docker
        uses: docker/login-action@v3
        with:
          username: taratrios
          password: ${{ secrets.DOCKER_HUB_AUTH }}
      - name: build image
        run: |
          docker build ./api -t taratrios/devops-qr-api:latest
          docker build ./front-end-nextjs -t taratrios/devops-nextjs:latest
      - name: push image to docker hub
        run: |
          docker push taratrios/devops-qr-api:latest
          docker push taratrios/devops-nextjs:latest
